//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        public int kullanici_id { get; set; }
        public string kullanici_ad { get; set; }
        public string kullanici_soyad { get; set; }
        public string kullanici_tc { get; set; }
        public string kullanici_mail { get; set; }
        public string kullanici_tel { get; set; }
        public Nullable<double> kullanici_ceza { get; set; }
        public string kullanici_cinsiyet { get; set; }
    }
}
